### ISSUE TITLE
Void World, No mob spawns

### ISSUE THREAD

**Issue by Dragnier** [TheRandomLabs/RandomTweaks#34] opened 2018-12-23 00:42 UTC
1. Make void world
2. Wait for/Make it night or create a mob spawner
3. No mobs spawn

**Comment by TheRandomLabs** [comment] 2018-12-23 01:29
This was apparently intended behavior, although I don't know why I didn't just make a config option. This will be fixed in 1.12.2-2.3.0.4.

**Closed as completed by TheRandomLabs** 2018-12-23 01:29 UTC

**Comment by Dragnier** [comment] 2018-12-23 02:30
Thanks. I'm constructing a modpack and planning to use the void world type for it, so it needs to be able to spawn mobs.
