### ISSUE TITLE
[Crash] When opening the controls menu, Minecraft crashes.

### ISSUE THREAD

**Issue by Qonsyuma** [TheRandomLabs/RandomTweaks#32] opened 2018-12-21 21:04 UTC
As I said in the title, this problem has been existing for me since multiple versions of this mod
( This crash also occurs without any other mods enabled, forge version is: 1.12.2-14.23.5.2796 )

If a crash log is needed, I'll be happy to DM it to the person needed

**Comment by TheRandomLabs** [comment] 2018-12-22 00:05
I can't reproduce this issue. Can I have a crash log?

**Comment by Qonsyuma** [comment] 2018-12-22 12:04
Sent over CurseForge!

**Comment by TheRandomLabs** [comment] 2018-12-23 01:28
I still have no idea why that's happening. However, I've attempted a fix which should be in 1.12.2-2.3.0.4 once I fix #33 and #34.

**Comment by TheRandomLabs** [comment] 2018-12-23 08:29
I've figured out why the crash is occurring. This is fixed in 1.12.2-2.4.0.1.

**Closed as completed by TheRandomLabs** 2018-12-23 08:29 UTC

**Comment by Qonsyuma** [comment] 2018-12-23 12:37
Thank's a lot! :)

**Comment by TheRandomLabs** [comment] 2018-12-23 12:37
No problem.
